steps:
- name: 'gcr.io/cloud-builders/npm:node-9.11.2'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm:node-9.11.2'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/npm:node-9.11.2'
  args: ['run', 'test']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--quiet', '--promote', '--stop-previous-version', '--project=$PROJECT_ID', 'build/app.yaml']